spring.datasource.url=jdbc:mysql://localhost:3306/terrarium_database
spring.datasource.username=zuzia
spring.datasource.password=zuzia

spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=
spring.security.user.password=